// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: internal/testutil/prototest/prototest.proto

package prototest

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on TestStruct with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TestStruct) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TestStruct with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TestStructMultiError, or
// nil if none found.
func (m *TestStruct) ValidateAll() error {
	return m.validate(true)
}

func (m *TestStruct) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TestName

	// no validation rules for TestId

	// no validation rules for TestDescription

	// no validation rules for TestStatus

	if len(errors) > 0 {
		return TestStructMultiError(errors)
	}

	return nil
}

// TestStructMultiError is an error wrapping multiple validation errors
// returned by TestStruct.ValidateAll() if the designated constraints aren't met.
type TestStructMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TestStructMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TestStructMultiError) AllErrors() []error { return m }

// TestStructValidationError is the validation error returned by
// TestStruct.Validate if the designated constraints aren't met.
type TestStructValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TestStructValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TestStructValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TestStructValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TestStructValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TestStructValidationError) ErrorName() string { return "TestStructValidationError" }

// Error satisfies the builtin error interface
func (e TestStructValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTestStruct.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TestStructValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TestStructValidationError{}
